export const REQUEST_BOOKMARKS = 'request bookmarks';
export const RECEIVE_BOOKMARKS = 'receive bookmarks';
export const BOOKMARK_FOR_EDIT = 'bookmark for edit';
export const EDIT_COMPONENT_STATE = 'edit component state';
export const UPDATE_DRAFT = 'update bookmark draft';
export const CLEAR_DRAFT = 'clear bookmark draft';
export const DELETE_BOOKMARK = 'delete bookmark';
export const ADD_BOOKMARK = 'add bookmark';
export const EDIT_BOOKMARK = 'edit bookmark';